service: rest
custom:
  tableName: 'blog-table-youracronym-${self:provider.stage}'
provider:
  name: aws
  apiKeys:
    - myFirstKey
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["BlogDynamoDBTable", "Arn" ] }
  environment:
    BLOG_TABLE: ${self:custom.tableName}
functions:
  get:
    handler: handler.get
    events:
      - http:
          path: blog/{id}
          private: true
          method: get
          cors: true
  put:
    handler: handler.put
    events:
      - http:
          path: blog/{id}
          private: true
          method: put
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: blog/{id}
          private: true
          method: delete
          cors: true
  post:
    handler: handler.post
    events:
      - http:
          path: blog
          method: post
          cors: true
          private: true
resources:
  Resources:
    BlogDynamoDBTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: blogId
            AttributeType: S
        KeySchema:
          -
            AttributeName: blogId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}  
